name: Deploy to Firebase

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build Vue App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
        env:
          VUE_APP_BASE_URL: "https://klassroom-demo.web.app/"
          VUE_APP_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          PROJECT_ID: "klassroom-demo"
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_KEY }}